version: '3.9'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 3333:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306